### ISSUE TITLE
Dataset guided

### ISSUE THREAD

**Issue by LiuJinzhe-Keepgoing** [gyhdog99/ecso#1]
Very meaningful work, thank you very much.

I'd love to follow this work, but I'm not very familiar with it. Can you provide the indicator evaluation code for the two data sets MM-SafetyBench and VLSafe?

Thanks

**Comment by gyhdog99** [comment]
> Very meaningful work, thank you very much.
> 
> I'd love to follow this work, but I'm not very familiar with it. Can you provide the indicator evaluation code for the two data sets MM-SafetyBench and VLSafe?
> 
> Thanks

Hi, sorry for the late replay. We have updated  scripts to reproduce the results in the paper, please see the instruction in the readme page.

**Comment by gyhdog99** [comment]
> Very meaningful work, thank you very much.
> 
> I'd love to follow this work, but I'm not very familiar with it. Can you provide the indicator evaluation code for the two data sets MM-SafetyBench and VLSafe?
> 
> Thanks

Hi, sorry for the late reply. We have updated scripts to reproduce the results in the paper, please see the instruction in the readme page.
