### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by AngelAlita** [gyhdog99/ecso#3]
hello，when i run mmsafe_tell_ask.sh， it occurs:RuntimeError: The size of tensor a (295) must match the size of tensor b (3) at non-singleton dimension 1.
![image](https://github.com/user-attachments/assets/3964c4b1-fa48-439f-95a2-5b5af5b2f451)

**Comment by snow-like-kk** [comment]
Hi, I came across the same error as well. Have you solved it?

**Comment by AngelAlita** [comment]
> Hi, I came across the same error as well. Have you solved it?

I have solved this issue. I believe the author intended for the model not to repeat the problem itself in the output. However, the output generated by the official LLaVA already does not include the input content.You can directly remove the check for whether the input and output match.Here are the modifications I made in the "llava/eval/model_mmsafe_tell_ask.py" file.I hope this can be helpful to you.
![image](https://github.com/user-attachments/assets/6941e75b-2c77-4c5a-8ead-f92b42253bb6)

**Comment by snow-like-kk** [comment]
Thanks very much!
